### ISSUE TITLE
Why Is NTP Port 123 Blocked when udp and tcp Outgoing Traffic is allowed?

### ISSUE THREAD

**Issue by GitCourser** [pylorak/TinyWall#10]
![20230501085655](https://user-images.githubusercontent.com/18594370/235386850-a5fb1611-ce40-461e-8bd4-0bfa3e8c4ca4.jpg)
![20230501085619](https://user-images.githubusercontent.com/18594370/235386852-6f05b83e-8fe4-4fad-b2ec-49363cafc8cd.jpg)

**Comment by systemop7** [comment]
You have to use **Unrestricted UDP and TCP Traffic**

**Comment by 9ao9ai9ar** [comment]
Probably because inbound connections are still blocked. See https://superuser.com/questions/1727784/why-open-123-udp-in-both-directions.
