### ISSUE TITLE
Service exception does not work

### ISSUE THREAD

**Issue by deogo** [pylorak/TinyWall#14]
I have express vpn service exceptions defined as
ExpressVPN App Service (C:\Program Files (x86)\ExpressVPN\services\ExpressVPN.AppService.exe)
ExpressVPN System Service (C:\Program Files (x86)\ExpressVPN\services\ExpressVPN.SystemService.exe)
both Unrestricted TCP/UPD traffic
But both keep showing as blocked in connections list
VPN only works while firewall is disabled
TinyWall 3.3.1

**Comment by spacewaffles309** [comment]
I don't have ExpressVPN to test with, but on some older versions of TinyWall, my ProtonVPN wouldn't connect at all unless I ticked "Unblock LAN traffic."  Have you tried that one?

**Comment by deogo** [comment]
I think I tried that too, still didn't work for some reason. And whole problem started to occur after certain ExpressVPN update. I wonder what they could do so it stopped working. Still love the app, anyway, it is best by simplicity and usability.

**Comment by systemop7** [comment]
Same type of thing happen when i tried to use IPVanish vpn.
But you have to look at "toolbar > Show connections" to take a look what is trying to access internet related to your vpn. 

Personally i see that when i select vpn protocol wireguard then it's properly working. other protocol like OpenVpn and IKEv2 is probably a mess.

**Comment by xroberx** [comment]
I have the exact same problem with ExpressVPN, could you please fix it? TinyWall is the best application firewall out there and I don't really want to switch to another application.

**Comment by gondwanasoft** [comment]
I have the same problem with gamingservices.exe. I've added exceptions for both exe and service, but it still lists as blocked.

FWIW, task manager lists two processes called 'GamingServices' but with different filenames. Could this confuse TinyWall?

**Comment by pylorak** [comment]
Please see #47.
