### ISSUE TITLE
Keyboard shortcuts put TinyWall on top and does not let you use the shortcut in other applications

### ISSUE THREAD

**Issue by jcesardias** [pylorak/TinyWall#18]
When I try to open the command palette in VSCode using Ctrl+Shift+P, it does not open the command palette because it opens the Processes window in TinyWall instead.

**Comment by jameslocks** [comment]
The option to custom set the hotkeys would be ideal.

@jcesardias as a work around, you can "disable global hotkeys" from the Manage window, General tab

**Comment by 9ao9ai9ar** [comment]
The option to set custom hotkeys is being tracked in [this issue](https://github.com/pylorak/TinyWall/issues/1).

**Comment by pylorak** [comment]
Current solution: See jameslocks' answer.
Alternative solution: feature request in #1.
