### ISSUE TITLE
When installing Win10, only 21H2 or above?

### ISSUE THREAD

**Issue by TheOncomingStorm** [pylorak/TinyWall#2]
I have some older Win10 media and when I install from it, if I try to install TinyWall too soon, it complains that 21H2 is required. Why is this required on Win10 but TW can apparently install on XP(?), Win7, etc. without issue? It's kinda annoying because the first thing I want to do is install a firewall and software and only after I've done that do I want to update Windows but with this I have to wait for the updates to take hold. I'm trying to build the perfect system image for QEMU/KVM so I have gone through this process about 10 times in the past 2 days alone and it has taken an extra hour each time. I prefer to do the updates once I'm done installing software so that the long portion of this process can happen while I'm asleep or the like.

**Comment by pylorak** [comment]
The 21H2 requirement is due to the new version 3.3, which does not support Win7/Win8/Win8.1 anymore.
Anyway, it seems you're updating your Windows anyway after installation, so the root of your problem is your outdated Windows install media. The most obvious solution is to use the latest. That way you can not only install the firewall immediately after Windows setup, but you'll also have a much faster update process.

**Comment by ilgrank** [comment]
@TheOncomingStorm : or, you can use tinywall **3.2**

**Comment by r3d4** [comment]
That meas TinyWall will no longer work on Windows 10 LTSC 2019 altough ist supported by Microsoft until 2029?
Please make it possible to run this great tool on LTSC 2019.

**Comment by ilgrank** [comment]
@r3d4 : you can use 3.2 on LTSC2019, it is fully functional (and no other update after 3.3 is planned anyways)

**Comment by pylorak** [comment]
Version 3.3 doesn't have any extra features compared to 3.2.5. The differences are 3.3's code is more cleaned up and contains additional optimizations. If you cannot install 3.3, just keep using 3.2.5 and you won't be missing out on anything.

**Comment by GitCourser** [comment]
> 

I also use ltsc2019, but I can't find the historical version to download on the website

**Comment by GitCourser** [comment]
May I know if the author has tested if there are any issues before Win10 21H2? I modified the MSI and forced it to install on Win10 LTSC 2019 (1809), and it works fine.

**Comment by GitCourser** [comment]
May I know if the author has tested if there are any issues before Win10 21H2? I modified the MSI and forced it to install on Win10 LTSC 2019 (1809), and it works fine.

**Comment by r3d4** [comment]
> @r3d4 : you can use 3.2 on LTSC2019, it is fully functional (and no other update after 3.3 is planned anyways)

Yeah, I already use 3.2 for a long time. But I was afraid that its not possible to run future versions on LTSC2019.
So for now I will stay with 3.2.5. 
Thanks
