### ISSUE TITLE
Old versions

### ISSUE THREAD

**Issue by mahfiaz** [pylorak/TinyWall#21]
Please keep links to old versions of TinyWall available, e.g version 3.2.5, which is the last version to run on Windows 7 and 8.

**Comment by Barough** [comment]
Old versions can be downloaded from here
https://tinywall.en.uptodown.com/windows/versions

**Comment by cemsterx** [comment]
Thank you for the thought but, the site is not available: "Due to maintenance, downloads are currently not available. We're working to restore the service as soon as possible. We apologize for any inconvenience this may cause you."

Additionally, the website's track record is not the best. It would be advisable to have the older versions available from a reliable source.

**Comment by Barough** [comment]
The site is back up and running but your right, Uptodown ain't the best place but it is what it is.

TinyWall's website or Github would be the best solution for hosting some older versions.

**Comment by cemsterx** [comment]
I am afraid this is what I get when I click on a version of the software:  "Due to maintenance, downloads are currently not available. We're working to restore the service as soon as possible. We apologize for any inconvenience this may cause you."

Then I tried another version and this is what I get: "Malwarebytes Browser Guard blocked this page because it may contain malicious activity. We strongly recommend you do not continue. You may be putting your safety at risk by visiting this site."

Not too promising...

**Comment by mahfiaz** [comment]
There should be a list of MD5, SHA256 etc checksums of installer files published in git, so you would know that the files you got have not been tampered with after the build.

**Comment by Damian-2001** [comment]
3.2.5 version date: dec 30, 2021.
MD5: 0052C01FECB20F84530B17EE57547AEA
SHA1: 551F15DEB31175DDD92B3E34B4524E86F9EFA7DE 
https://web.archive.org/web/20220401000000*/https://tinywall.pados.hu/download.php
https://web.archive.org/web/20220518181134/https://tinywall.pados.hu/files/TinyWall-v3-Installer.msi

**Comment by cemsterx** [comment]
I am so pissed that I deleted my older versions...

So, I have a bad news. I finally was able to riched the "https://tinywall.en.uptodown.com/windows/versions"

However, this is what I got: 

![0000000](https://github.com/pylorak/TinyWall/assets/47753229/a0379055-4d28-4112-8612-a40914462a8e)

**Comment by mahfiaz** [comment]
For the currently latest version both tinywall.pados.hu and tinywall.en.uptodown.com/windows/versions had identical files.

The checksums for 3.3.1 are below:

md5sum tinywall-3-3-1.msi
792984fcabfda6bfa2df1d6975f02dbe  tinywall-3-3-1.msi

sha256sum tinywall-3-3-1.msi
250b56eff2cd5316c6cf8c8b92cb5f29fb3849089e69c8138bf5dd9bd0e9e001  tinywall-3-3-1.msi

Size 1839104 bytes.

**Comment by mahfiaz** [comment]
> I am so pissed that I deleted my older versions... The version I have now is pretty much useless... It doesn't block anything. When I click on "show blocked connections" it is always "EMPTY" !!! I have never seen that page empty...
> 
> So, I have a bad news. I finally was able to get to the site. (https://tinywall.en.uptodown.com/windows/versions)
> 
> However, this is what I got:
> 
> ![0000000](https://user-images.githubusercontent.com/47753229/270642013-a0379055-4d28-4112-8612-a40914462a8e.png)

I upgraded to version 3.3.1, Tinywall works fine on up to date Windows 10 22H2, shows several blocked connections.

**Comment by cemsterx** [comment]
Interesting. The last time I tried to install 3.3.1_ I got the "not compatible with your OS" error. Also Win10 22H2...
I'll give it a try

By the way, the Malwarebytes warning wasn't for a specific file, but it was for the whole site...

**Comment by 9ao9ai9ar** [comment]
The link to download v3.2.5 (https://tinywall.pados.hu/files/TinyWall-v3.2.5.msi) can be found on the official website at https://tinywall.pados.hu/faq.php. I agree that, ideally, the binaries and SHA-256 checksums for all versions of TinyWall should be available on GitHub and/or the official website. Better yet, the installers should be signed. For now, make good use of [VirusTotal](https://www.virustotal.com) for some basic level of verification.

**Comment by pylorak** [comment]
If you need to run on pre-Wion10 computers, please use the download link found in the FAQ as 9ao9ai9ar has advised. It is the official and signed installer of TinyWall 3.2.5, and the last version that doesn't need Win10 or newer. Otherwise, please use the latest version of the software.

**Comment by pylorak** [comment]
> The link to download v3.2.5 (https://tinywall.pados.hu/files/TinyWall-v3.2.5.msi) can be found on the official website at https://tinywall.pados.hu/faq.php. I agree that, ideally, the binaries and SHA-256 checksums for all versions of TinyWall should be available on GitHub and/or the official website. Better yet, the installers should be signed. For now, make good use of [VirusTotal](https://www.virustotal.com) for some basic level of verification.

Actually, the installers are signed, have always been.
