### ISSUE TITLE
Feature Request: Popup when app is blocked for first time.

### ISSUE THREAD

**Issue by Mostlylost** [pylorak/TinyWall#22]
Title says it all.
:)

**Comment by tomazas** [comment]
I think this contradicts with the initial TinyWall "[no-popup approach](https://tinywall.pados.hu/features.php)" idea to not show any popups like other firewalls do. You will experience the actual blocking rather than get the popup.

**Comment by mehdismekouar** [comment]
I agree with @Mostlylost, i love the simplicity of the app and would love to have this feature on
I also agree with @tomazas and i suggest to have this feature as a checkbox in the settings if anyone like me wants it
Thanks
