### ISSUE TITLE
TW can't control executables that sits on network drives

### ISSUE THREAD

**Issue by gerroon** [pylorak/TinyWall#30]
Hi

I realized that if an app is run from a network drive, the rules by TW is not applied. Basically I can never unlock a process if it resides on a network drive.

I am on Windows 10 Pro x64, using 3.2.5

**Comment by madroots** [comment]
file upload in your browser also wont pick up files from network shares. This is common behaviour and although I cannot explain why it happens, its just the way it is. It might have to do something with the permissions.

**Comment by pylorak** [comment]
Cannot reproduce. Whitelisting an executable that resides on a network share works for me.

**Comment by pylorak** [comment]
> file upload in your browser also wont pick up files from network shares. This is common behaviour and although I cannot explain why it happens, its just the way it is. It might have to do something with the permissions.

There is neither a browser nor any kind of file upload functionality in TinyWall. You have confused TinyWall with some other software.

**Comment by pylorak** [comment]
Closed due to being stale and cannot repro, seems to work for me.
