### ISSUE TITLE
Feature request: Date when rule has added, column

### ISSUE THREAD

**Issue by kek001** [pylorak/TinyWall#33]
Date when rule has added, column

thanks,

**Comment by 9ao9ai9ar** [comment]
I actually think a "last modified" column would be more useful, but neither would be as useful as a "ports opened (permanent)" column together with a "ports opened (temporary)" column. I sometimes forget to change the exception lifetime to something other than "permanent", and the ports will be opened for longer than I desired and I'd have no way of finding it out without opening the rule edit dialog box.
