### ISSUE TITLE
Application refuses to build due to missing 'github_mark.png' in Icons.resx

### ISSUE THREAD

**Issue by TempAccountNull** [pylorak/TinyWall#34]
This won't build since you never uploaded the github_mark.png in img folder. 
I checked all previous commits and it wasn't there. 

So anyone attempting to build "TinyWall" from source, won't be able to unless they remove it.

Error:
> 1>TinyWall\SettingsForm.Designer.cs(448,77,448,88): error CS0117: 'Icons' does not contain a definition for 'github_mark'

Line: 448 in SettingsForm.Designer.cs
`this.btnGithub.Image = global::pylorak.TinyWall.Resources.Icons.github_mark;`

### To fix:
SettingsForm.Designer.cs comment this line out.
> this.btnGithub.Image = global::pylorak.TinyWall.Resources.Icons.github_mark;

Icons.resx remove the following lines
`<data name="github_mark" type="System.Resources.ResXFileRef, System.Windows.Forms">
     <value>img\github-mark.png;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a</value>
   </data>`

You will now be able to build it.

**Comment by pylorak** [comment]
Fixed in 5ea9e3af6ced668c44e1bf948b5f29abc9210bcf.
