### ISSUE TITLE
Feature request: Neutral search for filename in Internet

### ISSUE THREAD

**Issue by PeterP2** [pylorak/TinyWall#36]
I'd prefer it if not google was used as the search engine.
Perhaps the browser's custom search engine could be used instead?
(or search engine could be configurable?)

**Comment by pylorak** [comment]
There is no uniform way to start a search query across different browsers. This rules out using the default search engine configured by the user, as the solution would need to be specific to the currently installed (default) browser.

There is only a way cross-browser to start a specific URL. Hence TinyWall defaults to google.com for now, as it is by far the most used search engine.
