### ISSUE TITLE
Which Services Should Be Allowed for Windows Security?

### ISSUE THREAD

**Issue by Hana-Hikari** [pylorak/TinyWall#51]
Hi, Thanks for making this wonderful software.
I see TinyWall is blocking many Windows services, and I want to allow everything that's necessary for security.
I've compiled a list that I suspect I need to allow, and I'd appreciate your advice on which services should be enabled.
(Feature Request: An option for TinyWall to automatically allow anything essential for Windows security. Does it already exist?)

As seen in the attached image:
1. I have allowed "Windows Defender" in "Special Exceptions."
2. "smartscreen.exe" was blocked, so I allowed it in "Application Exceptions."
3. A list of possible candidates for allowing connectivity.

Thanks for any advice.

![main1](https://github.com/user-attachments/assets/f7d6744b-8742-4ae6-8d8b-5ff1d0d3c231)

**Comment by pylorak** [comment]
The virus definition and also the engine updates of Windows Defender are delivered using standard Windows updates. This means Windows Defender will be always up-to-date as long as you can run Windows Update. **This is true even if you disable Windows Defender in TinyWall's special exceptions.**

The special exception for Windows Defender in TinyWall controls automatically submitting sample files from your computer to Microsoft. As this is optional for the operation of Windows Defender and does not impede its operation on the end-user's computer, it is disabled by default for privacy concerns.

What other security-related Windows feature are you worried about specifically?

**Comment by Hana-Hikari** [comment]
Thanks for you answer.
"_Most_ of the screenshots of blocked processes you supplied are not relevant / not security-related." That's good to know! but do you know if allowing some of these or others would contribute to security more? for example: "smarscreen.exe", "MpDefenderCoreService.exe", or others?
Thanks

**Comment by pylorak** [comment]
I have no idea what MpDefenderCoreService.exe is about.

smartscreen.exe is responsible for SmartScreen which you might recognize from the following screenshot:
![microsoft-defender-smartscreen-warning](https://github.com/user-attachments/assets/de96f4bb-93b9-45ed-8d12-4af3db4c9544)
