### ISSUE TITLE
please, opensource TinyWallLegacy v3.2.5 !!!

### ISSUE THREAD

**Issue by DI555** [pylorak/TinyWall#8]
Many of us keep using win versions 7 and 8.., and even 32bits, and even more ReactOS (yet 32bits win compatible OS)..

so, please, make and keep opensourced TinyWallLegacy since after v3.2.5 !!!

**Comment by pylorak** [comment]
It is already open-source. The full git history is online here on GitHub, so all older versions can be rebuilt.

I'll update the official website though to provide a prebuilt installer also for v3.2.5 so Win7 user can install it.

**Comment by DI555** [comment]
@pylorak , oh, great!
could you put the builds here, in releases section, pls?

and, if the versions upper than 3.2.5 are on new code, may be better create a new repo here especially for 3.2.5 row?

**Comment by 9ao9ai9ar** [comment]
The prebuilt MSI installer for v3.2.5 can be found near the top of the FAQ section of the website at https://tinywall.pados.hu/faq.php. I believe this issue can be closed.

P.S. Does TinyWall even run on Windows XP, let alone ReactOS?

**Comment by pylorak** [comment]
> P.S. Does TinyWall even run on Windows XP, let alone ReactOS?

On XP it doesn't. On ReactOS, I have no idea.

**Comment by pylorak** [comment]
> Well, the v3.2.5 code is already here on GitHub in the commit history. Seeing that the author doesn't even answer to the opened issues or release a newer version of TinyWall, I doubt he'll have the time to review any pull requests for the legacy version. I suggest people interested in maintaining the legacy version of TinyWall just fork the repository and work on the improvements in their own repositories.

That is true, unfortunately. I'll keep v3.2.5 available for download so that users with older operating systems can still install TinyWall, but I don't intend to maintain that old version anymore. The source code of it however is available in this repository, correctly version-tagged.

Closing as v3.2.5 is already open-sourced.
